name: memo_api
description: Simple MVC-style Dart memo API
version: 1.0.0
repository: https://github.com/josufh/Dart-Memo-API

environment:
  sdk: ^3.12.1

dependencies:
  google_cloud_firestore: ^0.5.2
  shelf: ^1.4.2
  shelf_router: ^1.1.2

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
